---
image:
  file: ".devcontainer/gitpod.Dockerfile"
tasks:
- init: flutter doctor
  command: zsh
vscode:
  extensions:
  - coenraads.bracket-pair-colorizer-2
  - oderwat.indent-rainbow
  - zainchen.json
  - equinusocio.vsc-material-theme
  - equinusocio.vsc-material-theme-icons
  - dart-code.dart-code
  - dart-code.flutter
  - nash.awesome-flutter-snippets
  - alexisvt.flutter-snippets
  - luanpotter.dart-import
  - naco-siren.gradle-language
  - mathiasfrohlich.kotlin
