name: loveblocks
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  
  ## utils ##
  equatable: ^2.0.3
  logger: ^1.0.0
  formz: ^0.4.0

  ## widget ##
  font_awesome_flutter: ^9.1.0
  fluttertoast: ^8.0.7
  flutter_unity_widget: ^4.2.0

  ## firebase ##
  cloud_firestore: ^2.2.2
  cloud_functions: ^1.1.2
  firebase_analytics: ^8.1.2
  firebase_app_check: ^0.0.1+2
  firebase_crashlytics: ^2.0.6
  firebase_storage: ^8.1.3
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4

  ## state management ##
  beamer: ^0.14.1
  flutter_bloc: ^7.0.1

  ## custom ##
  loveblocks_proto:
    git:
      url: https://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@github.com/loveblocks-labs/hello-world-protobuf-definitions.git
      ref: 83d61ce65003fbee4bf620dea7a6fe1c465b78f5
      path: dart/loveblocks_proto
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true