
name: Lint Code Base
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  pull_request:
    branches: [main]
    
  workflow_dispatch:
 
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: ".*dart|.*/fastlane/.*|.vscode/.*|.*cs|.*proto|ios/.*|android/.*"

      ################################################
      # Clone Flutter repository with stable channel #
      ################################################
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: stable
      - run: flutter doctor -v

      ##########################
      # Flutter analyze & test #
      ##########################
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
