#
# Documents
# https://game.ci/docs/github/getting-started
#

name: Build Android
on:
  workflow_dispatch: 
    inputs:
        lane:
          description: 'Fastlane lane to use (beta OR firebase OR production)'
          required: true
          default: 'firebase'
 

jobs:
  buildAndroid:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-18.04
    env:
      PROJECT_PATH: ${{ format('{0}', github.workspace) }}
      ANDROID_BUILD_PATH: ${{ format('{0}/android', github.workspace) }}
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - unity/unity_project
        unityVersion:
          - 2019.4.27f1
        targetPlatform:
          - Android

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        # with:
          # lfs: true

      # Cache Library
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      
      # Cache Unity Grpc
      - name: Cache Unity Grpc
        id: cache-unity-grpc
        uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Assets/Plugins
          key: AssetsPlugins-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}

      - name: Download grpc_unity_package
        if: steps.cache-unity-grpc.outputs.cache-hit != 'true'
        id: terminal-download-grpc
        run: |
          curl -o ~/grpc_unity_package.zip "https://packages.grpc.io/archive/2021/07/3e19babc1e53a31b393ddc84f7c7b6fcd100e4ef-f5359c83-c239-4754-a5cf-ab95c15c7964/csharp/grpc_unity_package.2.39.0-dev202107011005.zip"
          unzip ~/grpc_unity_package.zip -d "${{ matrix.projectPath }}/Assets/"
          rm -f ~/grpc_unity_package.zip
      - run: ls ${{ matrix.projectPath }}/Assets/Plugins

      # Build Unity Android
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          allowDirtyBuild: true
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: Build.DoBuildAndroid

      # Check export result
      - run: sudo ls android/unityLibrary

      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: stable
      - run: flutter doctor -v

      # Before all, let `pub get`
      - run: flutter pub get

      # Run Fix File permission
      - name: Fix File Permissions
        id: terminal-fix-permissions
        run: |
          sudo chown -R $USER $PROJECT_PATH

      
      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: android
          
      # Build and deploy with Fastlane (by default, to beta track) 🚀.
      - name: Run fastlane deploy
        run: bundle exec fastlane ${{ github.event.inputs.lane || 'firebase' }}
        env:
          FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_CLI_TOKEN}}
          FIREBASEAPPDISTRO_GROUPS: ${{secrets.FIREBASEAPPDISTRO_GROUPS}}
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android

  